# pg_service.conf for minimally exercising libpq use of LDAP.
#
# pg_service.conf 用于最低程度地使用 LDAP 的 libpq。

# Having failed to reach an LDAP server, libpq essentially ignores the
#
# 由于未能到达 LDAP 服务器，libpq 本质上忽略了
# "service=test_ldap" in its connection string.  Contact the "discard"
#
# 其连接字符串中的“service=test_ldap”。  联系“丢弃”
# service; the test works whether or not it answers.
#
# 服务;无论测试是否有答案，测试都有效。
[test_ldap]
ldap://127.0.0.1:9/base?attribute?one?filter
