/*
 * contrib/pgcrypto/crypt-sha.c
 *
 * This implements shacrypt password hash functions and follows the
 * public available reference implementation from
 *
 * 这实现了 shacrypt 密码哈希函数，并遵循以下公开可用的参考实现
 *
 * https://www.akkadia.org/drepper/SHA-crypt.txt
 *
 * This code is public domain.
 *
 * 该代码是公共领域的。
 *
 * Please see the inline comments for details about the algorithm.
 *
 * 有关算法的详细信息，请参阅内嵌注释。
 *
 * Basically the following code implements password hashing with sha256 and
 * sha512 digest via OpenSSL. Additionally, an extended salt generation (see
 * crypt-gensalt.c for details) is provided, which generates a salt suitable
 * for either sha256crypt and sha512crypt password hash generation.
 *
 * 基本上，以下代码通过 OpenSSL 使用 sha256 和 sha512 摘要实现密码散列。此外，还提供了扩展的盐生成（有关详细信息，请参阅 crypt-gensalt.c），它生成适合 sha256crypt 和 sha512crypt 密码哈希生成的盐。
 *
 * Official identifiers for suitable password hashes used in salts are
 * 5 : sha256crypt and
 * 6 : sha512crypt
 *
 * 盐中使用的合适密码哈希的官方标识符是 5 : sha256crypt 和 6 : sha512crypt
 *
 * The hashing code below supports and uses salt length up to 16 bytes. Longer
 * input is possible, but any additional byte of the input is disregarded.
 * gen_salt(), when called with a sha256crypt or sha512crypt identifier will
 * always generate a 16 byte long salt string.
 *
 * 下面的哈希代码支持并使用最大 16 字节的盐长度。更长的输入是可能的，但输入的任何附加字节都将被忽略。 gen_salt()，当使用 sha256crypt 或 sha512crypt 标识符调用时，将始终生成 16 字节长的 salt 字符串。
 *
 * Output is compatible with any sha256crypt and sha512crypt output
 * generated by e.g. OpenSSL or libc crypt().
 *
 * 输出与例如生成的任何 sha256crypt 和 sha512crypt 输出兼容。 OpenSSL 或 libc crypt()。
 *
 * The described algorithm uses default computing rounds of 5000. Currently,
 * even when no specific rounds specification is used, we always explicitly
 * print out the rounds option flag with the final hash password string.
 *
 * 所描述的算法使用默认的计算轮次 5000。目前，即使没有使用特定的轮次规范，我们也总是显式地打印出带有最终哈希密码字符串的轮次选项标志。
 *
 * The length of the specific password hash (without magic bytes and salt
 * string) is:
 *
 * 特定密码哈希的长度（没有魔术字节和盐字符串）是：
 *
 * sha256crypt: 43 bytes and
 * sha512crypt: 86 bytes.
 *
 * sha256crypt：43 字节，sha512crypt：86 字节。
 *
 * Overall hashed password length is:
 *
 * 哈希密码的总长度为：
 *
 * sha256crypt: 80 bytes and
 * sha512crypt: 123 bytes
 *
 * sha256crypt：80 字节和 sha512crypt：123 字节
 *
 */
#include "postgres.h"

#include "common/string.h"
#include "mb/pg_wchar.h"
#include "miscadmin.h"

#include "px-crypt.h"
#include "px.h"

typedef enum
{
	PGCRYPTO_SHA256CRYPT = 0,
	PGCRYPTO_SHA512CRYPT = 1,
	PGCRYPTO_SHA_UNKOWN
} PGCRYPTO_SHA_t;

static const char _crypt_itoa64[64 + 1] =
"./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

/*
 * Modern UNIX password, based on SHA crypt hashes
 *
 * 现代 UNIX 密码，基于 SHA 加密哈希值
 */
char *
px_crypt_shacrypt(const char *pw, const char *salt, char *passwd, unsigned dstlen)
{
	static const char rounds_prefix[] = "rounds=";
	static const char *magic_bytes[2] = {"$5$", "$6$"};

	/* Used to create the password hash string
	 *
	 * 用于创建密码哈希字符串
	 */
	StringInfo	out_buf = NULL;

	PGCRYPTO_SHA_t type = PGCRYPTO_SHA_UNKOWN;
	PX_MD	   *digestA = NULL;
	PX_MD	   *digestB = NULL;
	int			err;

	const char *dec_salt_binary;	/* pointer into the real salt string */
	StringInfo	decoded_salt = NULL;	/* decoded salt string */
	unsigned char sha_buf[PX_SHACRYPT_DIGEST_MAX_LEN];

	/* temporary buffer for digests
	 *
	 * 摘要的临时缓冲区
	 */
	unsigned char sha_buf_tmp[PX_SHACRYPT_DIGEST_MAX_LEN];
	char		rounds_custom = 0;
	char	   *p_bytes = NULL;
	char	   *s_bytes = NULL;
	char	   *cp = NULL;
	const char *fp = NULL;		/* intermediate pointer within salt string */
	const char *ep = NULL;		/* holds pointer to the end of the salt string */
	size_t		buf_size = 0;	/* buffer size for sha256crypt/sha512crypt */
	unsigned int block;			/* number of bytes processed */
	uint32		rounds = PX_SHACRYPT_ROUNDS_DEFAULT;
	unsigned int len,
				salt_len = 0;

	/* Sanity checks
	 *
	 * 健全性检查
	 */
	if (!passwd)
		return NULL;

	if (pw == NULL)
		elog(ERROR, "null value for password rejected");

	if (salt == NULL)
		elog(ERROR, "null value for salt rejected");

	/*
	 * Make sure result buffers are large enough.
	 *
	 * 确保结果缓冲区足够大。
	 */
	if (dstlen < PX_SHACRYPT_BUF_LEN)
		elog(ERROR, "insufficient result buffer size to encrypt password");

	/* Init result buffer
	 *
	 * 初始化结果缓冲区
	 */
	out_buf = makeStringInfoExt(PX_SHACRYPT_BUF_LEN);
	decoded_salt = makeStringInfoExt(PX_SHACRYPT_SALT_MAX_LEN);

	/* Init contents of buffers properly
	 *
	 * 正确初始化缓冲区的内容
	 */
	memset(&sha_buf, '\0', sizeof(sha_buf));
	memset(&sha_buf_tmp, '\0', sizeof(sha_buf_tmp));

	/*
	 * Decode the salt string. We need to know how many rounds and which
	 * digest we have to use to hash the password.
	 *
	 * 解码盐字符串。我们需要知道必须使用多少轮和哪个摘要来哈希密码。
	 */
	len = strlen(pw);
	dec_salt_binary = salt;

	/*
	 * Analyze and prepare the salt string
	 *
	 * 分析并准备盐串
	 *
	 * The magic string should be specified in the first three bytes of the
	 * salt string.  Do some sanity checks first.
	 *
	 * 魔术字符串应在盐字​​符串的前三个字节中指定。  首先进行一些健全性检查。
	 */
	if (strlen(dec_salt_binary) < 3)
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("invalid salt"));

	/*
	 * Check format of magic bytes. These should define either 5=sha256crypt
	 * or 6=sha512crypt in the second byte, enclosed by ascii dollar signs.
	 *
	 * 检查魔术字节的格式。这些应该在第二个字节中定义 5=sha256crypt 或 6=sha512crypt，并用 ascii 美元符号括起来。
	 */
	if ((dec_salt_binary[0] != '$') || (dec_salt_binary[2] != '$'))
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("invalid format of salt"),
				errhint("magic byte format for shacrypt is either \"$5$\" or \"$6$\""));

	/*
	 * Check magic byte for supported shacrypt digest.
	 *
	 * 检查魔术字节是否支持 shacrypt 摘要。
	 *
	 * We're just interested in the very first 3 bytes of the salt string,
	 * since this defines the digest length to use.
	 *
	 * 我们只对盐字符串的前 3 个字节感兴趣，因为它定义了要使用的摘要长度。
	 */
	if (strncmp(dec_salt_binary, magic_bytes[0], strlen(magic_bytes[0])) == 0)
	{
		type = PGCRYPTO_SHA256CRYPT;
		dec_salt_binary += strlen(magic_bytes[0]);
	}
	else if (strncmp(dec_salt_binary, magic_bytes[1], strlen(magic_bytes[1])) == 0)
	{
		type = PGCRYPTO_SHA512CRYPT;
		dec_salt_binary += strlen(magic_bytes[1]);
	}

	/*
	 * dec_salt_binary pointer is positioned after the magic bytes now
	 *
	 * dec_salt_binary 指针现在位于魔术字节之后
	 *
	 * We extract any options in the following code branch. The only optional
	 * setting we need to take care of is the "rounds" option. Note that the
	 * salt generator already checked for invalid settings before, but we need
	 * to do it here again to protect against injection of wrong values when
	 * called without the generator.
	 *
	 * 我们在以下代码分支中提取所有选项。我们需要注意的唯一可选设置是“rounds”选项。请注意，盐生成器之前已经检查过无效设置，但我们需要在这里再次执行此操作，以防止在没有生成器的情况下调用时注入错误值。
	 *
	 * If there is any garbage added after the magic byte and the options/salt
	 * string, we don't treat this special: This is just absorbed as part of
	 * the salt with up to PX_SHACRYPT_SALT_LEN_MAX.
	 *
	 * 如果在魔术字节和选项/盐字符串之后添加了任何垃圾，我们不会对此进行特殊处理：这只是作为盐的一部分被吸收，最多为 PX_SHACRYPT_SALT_LEN_MAX。
	 *
	 * Unknown magic byte is handled further below.
	 *
	 * 下面进一步处理未知的魔术字节。
	 */
	if (strncmp(dec_salt_binary,
				rounds_prefix, sizeof(rounds_prefix) - 1) == 0)
	{
		const char *num = dec_salt_binary + sizeof(rounds_prefix) - 1;
		char	   *endp;
		int			srounds = strtoint(num, &endp, 10);

		if (*endp != '$')
			ereport(ERROR,
					errcode(ERRCODE_SYNTAX_ERROR),
					errmsg("could not parse salt options"));

		dec_salt_binary = endp + 1;

		/*
		 * We violate supported lower or upper bound of rounds, but in this
		 * case we change this value to the supported lower or upper value. We
		 * don't do this silently and print a NOTICE in such a case.
		 *
		 * 我们违反了支持的轮次下限或上限，但在这种情况下，我们将此值更改为支持的下限或上限。在这种情况下，我们不会默默地这样做并打印通知。
		 *
		 * Note that a salt string generated with gen_salt() would never
		 * generated such a salt string, since it would error out.
		 *
		 * 请注意，使用 gen_salt() 生成的盐字符串永远不会生成这样的盐字符串，因为它会出错。
		 *
		 * But Drepper's upstream reference implementation supports this when
		 * passing the salt string directly, so we maintain compatibility.
		 *
		 * 但 Drepper 的上游参考实现在直接传递盐字符串时支持这一点，因此我们保持兼容性。
		 */
		if (srounds > PX_SHACRYPT_ROUNDS_MAX)
		{
			ereport(NOTICE,
					errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),
					errmsg("rounds=%d exceeds maximum supported value (%d), using %d instead",
						   srounds, PX_SHACRYPT_ROUNDS_MAX,
						   PX_SHACRYPT_ROUNDS_MAX));
			srounds = PX_SHACRYPT_ROUNDS_MAX;
		}
		else if (srounds < PX_SHACRYPT_ROUNDS_MIN)
		{
			ereport(NOTICE,
					errcode(ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE),
					errmsg("rounds=%d is below supported value (%d), using %d instead",
						   srounds, PX_SHACRYPT_ROUNDS_MIN,
						   PX_SHACRYPT_ROUNDS_MIN));
			srounds = PX_SHACRYPT_ROUNDS_MIN;
		}

		rounds = (uint32) srounds;
		rounds_custom = 1;
	}

	/*
	 * Choose the correct digest length and add the magic bytes to the result
	 * buffer. Also handle possible invalid magic byte we've extracted above.
	 *
	 * 选择正确的摘要长度并将魔术字节添加到结果缓冲区。还要处理我们上面提取的可能无效的魔术字节。
	 */
	switch (type)
	{
		case PGCRYPTO_SHA256CRYPT:
			{
				/* Two PX_MD objects required
				 *
				 * 需要两个 PX_MD 对象
				 */
				err = px_find_digest("sha256", &digestA);
				if (err)
					goto error;

				err = px_find_digest("sha256", &digestB);
				if (err)
					goto error;

				/* digest buffer length is 32 for sha256
				 *
				 * sha256 的摘要缓冲区长度为 32
				 */
				buf_size = 32;

				appendStringInfoString(out_buf, magic_bytes[0]);
				break;
			}

		case PGCRYPTO_SHA512CRYPT:
			{
				/* Two PX_MD objects required
				 *
				 * 需要两个 PX_MD 对象
				 */
				err = px_find_digest("sha512", &digestA);
				if (err)
					goto error;

				err = px_find_digest("sha512", &digestB);
				if (err)
					goto error;

				buf_size = PX_SHACRYPT_DIGEST_MAX_LEN;

				appendStringInfoString(out_buf, magic_bytes[1]);
				break;
			}

		case PGCRYPTO_SHA_UNKOWN:
			elog(ERROR, "unknown crypt identifier \"%c\"", salt[1]);
	}

	if (rounds_custom > 0)
		appendStringInfo(out_buf, "rounds=%u$", rounds);

	/*
	 * We need the real decoded salt string from salt input, this is every
	 * character before the last '$' in the preamble. Append every compatible
	 * character up to PX_SHACRYPT_SALT_MAX_LEN to the result buffer. Note
	 * that depending on the input, there might be no '$' marker after the
	 * salt, when there is no password hash attached at the end.
	 *
	 * 我们需要来自盐输入的真实解码盐字符串，这是前导码中最后一个“$”之前的每个字符。将最多 PX_SHACRYPT_SALT_MAX_LEN 的每个兼容字符附加到结果缓冲区。请注意，根据输入的不同，当末尾没有附加密码哈希时，盐后可能没有“$”标记。
	 *
	 * We try hard to recognize mistakes, but since we might get an input
	 * string which might also have the password hash after the salt string
	 * section we give up as soon we reach the end of the input or if there
	 * are any bytes consumed for the salt string until we reach the first '$'
	 * marker thereafter.
	 *
	 * 我们努力识别错误，但由于我们可能会得到一个输入字符串，该字符串在盐字符串部分之后也可能包含密码哈希，因此一旦到达输入末尾，或者盐字符串消耗了任何字节，直到我们到达第一个“$”标记，我们就会放弃。
	 */
	for (ep = dec_salt_binary;
		 *ep && ep < (dec_salt_binary + PX_SHACRYPT_SALT_MAX_LEN);
		 ep++)
	{
		/*
		 * Filter out any string which shouldn't be here.
		 *
		 * 过滤掉不应该出现在这里的任何字符串。
		 *
		 * First check for accidentally embedded magic strings here. We don't
		 * support '$' in salt strings anyways and seeing a magic byte trying
		 * to identify shacrypt hashes might indicate that something went
		 * wrong when generating this salt string. Note that we later check
		 * for non-supported literals anyways, but any '$' here confuses us at
		 * this point.
		 *
		 * 首先检查这里是否意外嵌入了魔法字符串。无论如何，我们不支持盐字符串中的“$”，并且看到尝试识别 shacrypt 哈希值的魔术字节可能表明生成此盐字符串时出现了问题。请注意，无论如何，我们稍后都会检查不支持的文字，但此时这里的任何“$”都会让我们感到困惑。
		 */
		fp = strstr(dec_salt_binary, magic_bytes[0]);
		if (fp != NULL)
			elog(ERROR, "bogus magic byte found in salt string");

		fp = strstr(dec_salt_binary, magic_bytes[1]);
		if (fp != NULL)
			elog(ERROR, "bogus magic byte found in salt string");

		/*
		 * This looks very strict, but we assume the caller did something
		 * wrong when we see a "rounds=" option here.
		 *
		 * 这看起来非常严格，但当我们在这里看到“rounds=”选项时，我们假设调用者做错了什么。
		 */
		fp = strstr(dec_salt_binary, rounds_prefix);
		if (fp != NULL)
			elog(ERROR, "invalid rounds option specified in salt string");

		if (*ep != '$')
		{
			if (strchr(_crypt_itoa64, *ep) != NULL)
				appendStringInfoCharMacro(decoded_salt, *ep);
			else
				ereport(ERROR,
						errcode(ERRCODE_INVALID_PARAMETER_VALUE),
						errmsg("invalid character in salt string: \"%.*s\"",
							   pg_mblen_cstr(ep), ep));
		}
		else
		{
			/*
			 * We encountered a '$' marker. Check if we already absorbed some
			 * bytes from input. If true, we are optimistic and terminate at
			 * this stage. If not, we try further.
			 *
			 * 我们遇到了“$”标记。检查我们是否已经从输入中吸收了一些字节。如果属实，我们持乐观态度并在现阶段终止。如果没有，我们会进一步尝试。
			 *
			 * If we already consumed enough bytes for the salt string,
			 * everything that is after this marker is considered to be part
			 * of an optionally specified password hash and ignored.
			 *
			 * 如果我们已经为盐字符串消耗了足够的字节，则该标记之后的所有内容都将被视为可选指定的密码哈希的一部分并被忽略。
			 */
			if (decoded_salt->len > 0)
				break;
		}
	}

	salt_len = decoded_salt->len;
	appendStringInfoString(out_buf, decoded_salt->data);
	elog(DEBUG1, "using salt \"%s\", salt len = %d, rounds = %u",
		 decoded_salt->data, decoded_salt->len, rounds);

	/*
	 * Sanity check: at this point the salt string buffer must not exceed
	 * expected size.
	 *
	 * 健全性检查：此时盐字符串缓冲区不得超过预期大小。
	 */
	if (out_buf->len > (3 + 17 * rounds_custom + salt_len))
		elog(ERROR, "unexpected length of salt string");

	/*-
	 * 1. Start digest A
	 * 2. Add the password string to digest A
	 * 3. Add the salt to digest A
	 *
	 * 1. 启动摘要 A 2. 添加密码字符串以摘要 A 3. 添加盐以摘要 A
	 */
	px_md_update(digestA, (const unsigned char *) pw, len);
	px_md_update(digestA, (const unsigned char *) decoded_salt->data, salt_len);

	/*-
	 * 4. Create digest B
	 * 5. Add password to digest B
	 * 6. Add the salt string to digest B
	 * 7. Add the password again to digest B
	 * 8. Finalize digest B
	 *
	 * 4. 创建摘要 B 5. 向摘要 B 添加密码 6. 向摘要 B 添加盐字符串 7. 再次向摘要 B 添加密码 8. 完成摘要 B
	 */
	px_md_update(digestB, (const unsigned char *) pw, len);
	px_md_update(digestB, (const unsigned char *) dec_salt_binary, salt_len);
	px_md_update(digestB, (const unsigned char *) pw, len);
	px_md_finish(digestB, sha_buf);

	/*
	 * 9. For each block (excluding the NULL byte), add digest B to digest A.
	 *
	 * 9. 对于每个块（不包括 NULL 字节），将摘要 B 添加到摘要 A。
	 */
	for (block = len; block > buf_size; block -= buf_size)
		px_md_update(digestA, sha_buf, buf_size);

	/*-
	 * 10. For the remaining N bytes of the password string, add the first N
	 * bytes of digest B to A.
	 *
	 * 10. 对于密码字符串的剩余 N 个字节，将摘要 B 的前 N ​​个字节添加到 A。
	 */
	px_md_update(digestA, sha_buf, block);

	/*-
	 * 11. For each bit of the binary representation of the length of the
	 * password string up to and including the highest 1-digit, starting from
	 * to lowest bit position (numeric value 1)
	 *
	 * 11. 对于密码字符串长度的二进制表示形式的每一位（含最高 1 位），从最低位位置开始（数值 1）
	 *
	 * a) for a 1-digit add digest B (sha_buf) to digest A
	 * b) for a 0-digit add the password string
	 *
	 * a) 对于 1 位数字，添加摘要 B (sha_buf) 以摘要 A b) 对于 0 位数字，添加密码字符串
	 */
	block = len;
	while (block)
	{
		px_md_update(digestA,
					 (block & 1) ? sha_buf : (const unsigned char *) pw,
					 (block & 1) ? buf_size : len);

		/* right shift to next byte
		 *
		 * 右移到下一个字节
		 */
		block >>= 1;
	}

	/* 12. Finalize digest A
	 *
	 * 12. 完成摘要 A
	 */
	px_md_finish(digestA, sha_buf);

	/* 13. Start digest DP
	 *
	 * 13. 启动摘要DP
	 */
	px_md_reset(digestB);

	/*-
	 * 14 Add every byte of the password string (excluding trailing NULL)
	 * to the digest DP
	 *
	 * 14 将密码字符串的每个字节（不包括尾随 NULL）添加到摘要 DP
	 */
	for (block = len; block > 0; block--)
		px_md_update(digestB, (const unsigned char *) pw, len);

	/* 15. Finalize digest DP
	 *
	 * 15. 完成摘要 DP
	 */
	px_md_finish(digestB, sha_buf_tmp);

	/*-
	 * 16. produce byte sequence P with same length as password.
	 *     a) for each block of 32 or 64 bytes of length of the password
	 *        string the entire digest DP is used
	 *     b) for the remaining N (up to  31 or 63) bytes use the
	 *        first N bytes of digest DP
	 *
	 * 16.产生与密码长度相同的字节序列P。 a) 对于密码字符串的每个 32 或 64 字节长度的块，使用整个摘要 DP b) 对于剩余的 N（最多 31 或 63）字节，使用摘要 DP 的前 N ​​个字节
	 */
	if ((p_bytes = palloc0(len)) == NULL)
	{
		goto error;
	}

	/* N step of 16, copy over the bytes from password
	 *
	 * 第 N 步，共 16 步，复制密码中的字节
	 */
	for (cp = p_bytes, block = len; block > buf_size; block -= buf_size, cp += buf_size)
		memcpy(cp, sha_buf_tmp, buf_size);
	memcpy(cp, sha_buf_tmp, block);

	/*
	 * 17. Start digest DS
	 *
	 * 17. 启动摘要 DS
	 */
	px_md_reset(digestB);

	/*-
	 * 18. Repeat the following 16+A[0] times, where A[0] represents the first
	 *    byte in digest A interpreted as an 8-bit unsigned value
	 *    add the salt to digest DS
	 *
	 * 18. 重复以下16+A[0]次，其中A[0]代表摘要A中的第一个字节，解释为8位无符号值，将salt添加到摘要DS中
	 */
	for (block = 16 + sha_buf[0]; block > 0; block--)
		px_md_update(digestB, (const unsigned char *) dec_salt_binary, salt_len);

	/*
	 * 19. Finalize digest DS
	 *
	 * 19. 完成摘要 DS
	 */
	px_md_finish(digestB, sha_buf_tmp);

	/*-
	 * 20. Produce byte sequence S of the same length as the salt string where
	 *
	 * 20. 生成与 salt 字符串长度相同的字节序列 S，其中
	 *
	 * a) for each block of 32 or 64 bytes of length of the salt string the
	 *    entire digest DS is used
	 *
	 * a) 对于盐字符串的每个 32 或 64 字节长度的块，使用整个摘要 DS
	 *
	 * b) for the remaining N (up to  31 or 63) bytes use the first N
	 *    bytes of digest DS
	 *
	 * b) 对于剩余的 N（最多 31 或 63）字节，使用摘要 DS 的前 N ​​个字节
	 */
	if ((s_bytes = palloc0(salt_len)) == NULL)
		goto error;

	for (cp = s_bytes, block = salt_len; block > buf_size; block -= buf_size, cp += buf_size)
		memcpy(cp, sha_buf_tmp, buf_size);
	memcpy(cp, sha_buf_tmp, block);

	/* Make sure we don't leave something important behind
	 *
	 * 确保我们不会留下重要的东西
	 */
	px_memset(&sha_buf_tmp, 0, sizeof sha_buf);

	/*-
	 * 21. Repeat a loop according to the number specified in the rounds=<N>
	 *     specification in the salt (or the default value if none is
	 *     present).  Each round is numbered, starting with 0 and up to N-1.
	 *
	 * 21. 根据 salt 中 rounds=<N> 规范中指定的数字（如果不存在则使用默认值）重复循环。  每轮都有编号，从 0 开始，到 N-1。
	 *
	 *     The loop uses a digest as input.  In the first round it is the
	 *     digest produced in step 12.  In the latter steps it is the digest
	 *     produced in step 21.h of the previous round.  The following text
	 *     uses the notation "digest A/B" to describe this behavior.
	 *
	 * 该循环使用摘要作为输入。  在第一轮中，它是步骤 12 中生成的摘要。在后面的步骤中，它是上一轮步骤 21.h 中生成的摘要。  以下文本使用符号“摘要 A/B”来描述此行为。
	 */
	for (block = 0; block < rounds; block++)
	{
		/*
		 * Make it possible to abort in case large values for "rounds" are
		 * specified.
		 *
		 * 如果指定了较大的“轮次”值，则可以中止。
		 */
		CHECK_FOR_INTERRUPTS();

		/* a) start digest B
		 *
		 * a) 开始摘要B
		 */
		px_md_reset(digestB);

		/*-
		 * b) for odd round numbers add the byte sequence P to digest B
		 * c) for even round numbers add digest A/B
		 *
		 * b) 对于奇数轮数，将字节序列 P 添加到摘要 B c) 对于偶数轮数，添加摘要 A/B
		 */
		px_md_update(digestB,
					 (block & 1) ? (const unsigned char *) p_bytes : sha_buf,
					 (block & 1) ? len : buf_size);

		/* d) for all round numbers not divisible by 3 add the byte sequence S
		 *
		 * d) 对于所有不能被 3 整除的整数，添加字节序列 S
		 */
		if ((block % 3) != 0)
			px_md_update(digestB, (const unsigned char *) s_bytes, salt_len);

		/* e) for all round numbers not divisible by 7 add the byte sequence P
		 *
		 * e) 对于所有不能被 7 整除的整数，添加字节序列 P
		 */
		if ((block % 7) != 0)
			px_md_update(digestB, (const unsigned char *) p_bytes, len);

		/*-
		 * f) for odd round numbers add digest A/C
		 * g) for even round numbers add the byte sequence P
		 *
		 * f) 对于奇数轮数添加摘要 A/C g) 对于偶数轮数添加字节序列 P
		 */
		px_md_update(digestB,
					 (block & 1) ? sha_buf : (const unsigned char *) p_bytes,
					 (block & 1) ? buf_size : len);

		/* h) finish digest C.
		 *
		 * h) 完成摘要 C.
		 */
		px_md_finish(digestB, sha_buf);
	}

	px_md_free(digestA);
	px_md_free(digestB);

	digestA = NULL;
	digestB = NULL;

	pfree(s_bytes);
	pfree(p_bytes);

	s_bytes = NULL;
	p_bytes = NULL;

	/* prepare final result buffer
	 *
	 * 准备最终结果缓冲区
	 */
	appendStringInfoCharMacro(out_buf, '$');

#define b64_from_24bit(B2, B1, B0, N)                                    \
	do {                                                                 \
		unsigned int w = ((B2) << 16) | ((B1) << 8) | (B0);              \
		int		i = (N);                                                 \
		while (i-- > 0)                                                  \
		{                                                                \
			appendStringInfoCharMacro(out_buf, _crypt_itoa64[w & 0x3f]); \
			w >>= 6;                                                     \
		}                                                                \
	} while (0)

	switch (type)
	{
		case PGCRYPTO_SHA256CRYPT:
			{
				b64_from_24bit(sha_buf[0], sha_buf[10], sha_buf[20], 4);
				b64_from_24bit(sha_buf[21], sha_buf[1], sha_buf[11], 4);
				b64_from_24bit(sha_buf[12], sha_buf[22], sha_buf[2], 4);
				b64_from_24bit(sha_buf[3], sha_buf[13], sha_buf[23], 4);
				b64_from_24bit(sha_buf[24], sha_buf[4], sha_buf[14], 4);
				b64_from_24bit(sha_buf[15], sha_buf[25], sha_buf[5], 4);
				b64_from_24bit(sha_buf[6], sha_buf[16], sha_buf[26], 4);
				b64_from_24bit(sha_buf[27], sha_buf[7], sha_buf[17], 4);
				b64_from_24bit(sha_buf[18], sha_buf[28], sha_buf[8], 4);
				b64_from_24bit(sha_buf[9], sha_buf[19], sha_buf[29], 4);
				b64_from_24bit(0, sha_buf[31], sha_buf[30], 3);

				break;
			}

		case PGCRYPTO_SHA512CRYPT:
			{
				b64_from_24bit(sha_buf[0], sha_buf[21], sha_buf[42], 4);
				b64_from_24bit(sha_buf[22], sha_buf[43], sha_buf[1], 4);
				b64_from_24bit(sha_buf[44], sha_buf[2], sha_buf[23], 4);
				b64_from_24bit(sha_buf[3], sha_buf[24], sha_buf[45], 4);
				b64_from_24bit(sha_buf[25], sha_buf[46], sha_buf[4], 4);
				b64_from_24bit(sha_buf[47], sha_buf[5], sha_buf[26], 4);
				b64_from_24bit(sha_buf[6], sha_buf[27], sha_buf[48], 4);
				b64_from_24bit(sha_buf[28], sha_buf[49], sha_buf[7], 4);
				b64_from_24bit(sha_buf[50], sha_buf[8], sha_buf[29], 4);
				b64_from_24bit(sha_buf[9], sha_buf[30], sha_buf[51], 4);
				b64_from_24bit(sha_buf[31], sha_buf[52], sha_buf[10], 4);
				b64_from_24bit(sha_buf[53], sha_buf[11], sha_buf[32], 4);
				b64_from_24bit(sha_buf[12], sha_buf[33], sha_buf[54], 4);
				b64_from_24bit(sha_buf[34], sha_buf[55], sha_buf[13], 4);
				b64_from_24bit(sha_buf[56], sha_buf[14], sha_buf[35], 4);
				b64_from_24bit(sha_buf[15], sha_buf[36], sha_buf[57], 4);
				b64_from_24bit(sha_buf[37], sha_buf[58], sha_buf[16], 4);
				b64_from_24bit(sha_buf[59], sha_buf[17], sha_buf[38], 4);
				b64_from_24bit(sha_buf[18], sha_buf[39], sha_buf[60], 4);
				b64_from_24bit(sha_buf[40], sha_buf[61], sha_buf[19], 4);
				b64_from_24bit(sha_buf[62], sha_buf[20], sha_buf[41], 4);
				b64_from_24bit(0, 0, sha_buf[63], 2);

				break;
			}

		case PGCRYPTO_SHA_UNKOWN:
			/* we shouldn't land here ...
			 *
			 * 我们不应该降落在这里...
			 */
			elog(ERROR, "unsupported digest length");
	}

	/*
	 * Copy over result to specified buffer.
	 *
	 * 将结果复制到指定的缓冲区。
	 *
	 * The passwd character buffer should have at least PX_SHACRYPT_BUF_LEN
	 * allocated, since we checked above if dstlen is smaller than
	 * PX_SHACRYPT_BUF_LEN (which also includes the NULL byte).
	 *
	 * passwd 字符缓冲区应至少分配 PX_SHACRYPT_BUF_LEN，因为我们在上面检查了 dstlen 是否小于 PX_SHACRYPT_BUF_LEN（还包括 NULL 字节）。
	 *
	 * In that case we would have failed above already.
	 *
	 * 如果那样的话，我们上面的操作就已经失败了。
	 */
	memcpy(passwd, out_buf->data, out_buf->len);

	/* make sure nothing important is left behind
	 *
	 * 确保没有留下任何重要的东西
	 */
	px_memset(&sha_buf, 0, sizeof sha_buf);
	destroyStringInfo(out_buf);
	destroyStringInfo(decoded_salt);

	/* ...and we're done
	 *
	 * ...我们就完成了
	 */
	return passwd;

error:
	if (digestA != NULL)
		px_md_free(digestA);

	if (digestB != NULL)
		px_md_free(digestB);

	destroyStringInfo(out_buf);
	destroyStringInfo(decoded_salt);

	ereport(ERROR,
			errcode(ERRCODE_INTERNAL_ERROR),
			errmsg("cannot create encrypted password"));
	return NULL;				/* keep compiler quiet */
}
