/*
 * This is a copy LLVM source code modified by the PostgreSQL project.
 * See SectionMemoryManager.cpp for notes on provenance and license.
 */
/*
 * 这是由 PostgreSQL 项目修改后的 LLVM 源码副本。
 * 有关出处和许可证的说明，请参见 SectionMemoryManager.cpp。
 */

//===- SectionMemoryManager.h - Memory manager for MCJIT/RtDyld -*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file contains the declaration of a section-based memory manager used by
// the MCJIT execution engine and RuntimeDyld.
//
// 此文件包含 MCJIT 执行引擎和 RuntimeDyld 所使用的基于节（section）的内存管理器的声明。
//
//===----------------------------------------------------------------------===//

/*
 * SectionMemoryManager 核心流程说明：
 *
 * SectionMemoryManager 是一个基于节（section）的内存管理器，专门用于管理 JIT（Just-In-Time）
 * 编译生成的机器码和数据的生命周期。它在 RuntimeDyld 加载对象文件时扮演着关键角色。
 *
 * 核心执行流程：
 * 1. 初始化：SectionMemoryManager 维护三个 MemoryGroup，分别用于存放可执行代码（CodeMem）、
 *    只读数据（RODataMem）和读写数据（RWDataMem）。
 * 2. 空间预留（可选）：通过 reserveAllocationSpace，可以一次性从系统申请一大块内存，
 *    以确保 code 和 data 节在虚拟地址空间中彼此靠近（这对于某些 CPU 架构的寻址非常重要）。
 * 3. 动态分配：当 RuntimeDyld 解析对象文件时，它会调用 allocateCodeSection 和
 *    allocateDataSection。管理器会从对应的 MemoryGroup 中划出内存块。初始状态下，
 *    这些内存块通常被设置为“读写”权限，以便 RuntimeDyld 进行写入和重定位操作。
 * 4. 完成与权限切换：当所有重定位完成后，调用 finalizeMemory()。
 *    此函数会将原本处于“读写”权限的内存块按照需求进行权限转化：
 *    - 代码块通常变为“只读+可执行”（RX）。
 *    - 只读数据块变为“只读”（RO）。
 *    - 读写数据块保持“读写”（RW）。
 * 5. 缓存刷新：在修改完内存权限后，管理器会调用 invalidateInstructionCache() 来刷新 CPU
 *    的指令缓存。这是确保 CPU 不会执行到旧内容的关键。
 */

#ifndef LLVM_EXECUTIONENGINE_BACKPORT_SECTIONMEMORYMANAGER_H
#define LLVM_EXECUTIONENGINE_BACKPORT_SECTIONMEMORYMANAGER_H

#include <llvm/ADT/SmallVector.h>
#include <llvm/ExecutionEngine/RTDyldMemoryManager.h>
#include <llvm/Support/Alignment.h>
#include <llvm/Support/Memory.h>
#include <cstdint>
#include <string>
#include <system_error>

namespace llvm {
namespace backport {

/// This is a simple memory manager which implements the methods called by
/// the RuntimeDyld class to allocate memory for section-based loading of
/// objects, usually those generated by the MCJIT execution engine.
///
/// 这是一个简单的内存管理器，它实现了 RuntimeDyld 类调用的方法，用于为基于节的对象加载分配内存，
/// 这些对象通常由 MCJIT 执行引擎生成。
///
/// This memory manager allocates all section memory as read-write.  The
/// RuntimeDyld will copy JITed section memory into these allocated blocks
/// and perform any necessary linking and relocations.
///
/// 该内存管理器将所有节内存分配为读写模式。RuntimeDyld 将把 JIT 生成的节内存拷贝到这些分配的块中，
/// 并执行任何必要的链接和重定位。
///
/// Any client using this memory manager MUST ensure that section-specific
/// page permissions have been applied before attempting to execute functions
/// in the JITed object.  Permissions can be applied either by calling
/// MCJIT::finalizeObject or by calling SectionMemoryManager::finalizeMemory
/// directly.  Clients of MCJIT should call MCJIT::finalizeObject.
///
/// 任何使用该内存管理器的客户端在尝试执行 JIT 对象中的函数之前，必须确保已应用了特定于节的页面权限。
/// 权限可以通过调用 MCJIT::finalizeObject 或直接调用 SectionMemoryManager::finalizeMemory 来应用。
/// MCJIT 的客户端通常应调用 MCJIT::finalizeObject。
class SectionMemoryManager : public RTDyldMemoryManager {
public:
  /// This enum describes the various reasons to allocate pages from
  /// allocateMappedMemory.
  ///
  /// 此枚举描述了从 allocateMappedMemory 分配页面的各种原因。
  enum class AllocationPurpose {
    Code,
    ROData,
    RWData,
  };

  /// Implementations of this interface are used by SectionMemoryManager to
  /// request pages from the operating system.
  ///
  /// 此接口的实现由 SectionMemoryManager 用于向操作系统请求页面。
  class MemoryMapper {
  public:
    /// This method attempts to allocate \p NumBytes bytes of virtual memory for
    /// \p Purpose.  \p NearBlock may point to an existing allocation, in which
    /// case an attempt is made to allocate more memory near the existing block.
    /// The actual allocated address is not guaranteed to be near the requested
    /// address.  \p Flags is used to set the initial protection flags for the
    /// block of the memory.  \p EC [out] returns an object describing any error
    /// that occurs.
    ///
    /// 此方法尝试为 \p Purpose 分配 \p NumBytes 字节的虚拟内存。\p NearBlock 可能指向现有分配，
    /// 在这种情况下，将尝试在现有块附近分配更多内存。实际分配的地址不保证靠近请求的地址。
    /// \p Flags 用于设置内存块的初始保护标志。\p EC [输出] 返回描述发生的任何错误的对象。
    ///
    /// This method may allocate more than the number of bytes requested.  The
    /// actual number of bytes allocated is indicated in the returned
    /// MemoryBlock.
    ///
    /// 此方法分配的字节数可能超过请求的数量。实际分配的字节数在返回的 MemoryBlock 中指出。
    ///
    /// The start of the allocated block must be aligned with the system
    /// allocation granularity (64K on Windows, page size on Linux).  If the
    /// address following \p NearBlock is not so aligned, it will be rounded up
    /// to the next allocation granularity boundary.
    ///
    /// 分配块的起始位置必须与系统分配粒度对齐（Windows 上为 64K，Linux 上为页面大小）。
    /// 如果紧随 \p NearBlock 之后的地址未对齐，它将被向上舍入到下一个分配粒度边界。
    ///
    /// \r a non-null MemoryBlock if the function was successful, otherwise a
    /// null MemoryBlock with \p EC describing the error.
    ///
    /// \r 如果函数成功，则返回非空的 MemoryBlock，否则返回空的 MemoryBlock，并由 \p EC 描述错误。
    virtual sys::MemoryBlock
    allocateMappedMemory(AllocationPurpose Purpose, size_t NumBytes,
                         const sys::MemoryBlock *const NearBlock,
                         unsigned Flags, std::error_code &EC) = 0;

    /// This method sets the protection flags for a block of memory to the state
    /// specified by \p Flags.  The behavior is not specified if the memory was
    /// not allocated using the allocateMappedMemory method.
    /// \p Block describes the memory block to be protected.
    /// \p Flags specifies the new protection state to be assigned to the block.
    ///
    /// 此方法将内存块的保护标志设置为 \p Flags 指定的状态。如果内存不是使用 allocateMappedMemory 
    /// 方法分配的，则其行为是未定义的。\p Block 描述要保护的内存块。
    /// \p Flags 指定要分配给该块的新保护状态。
    ///
    /// If \p Flags is MF_WRITE, the actual behavior varies with the operating
    /// system (i.e. MF_READ | MF_WRITE on Windows) and the target architecture
    /// (i.e. MF_WRITE -> MF_READ | MF_WRITE on i386).
    ///
    /// 如果 \p Flags 为 MF_WRITE，则实际行为随操作系统（例如 Windows 上的 MF_READ | MF_WRITE）
    /// 和目标架构（例如 i386 上的 MF_WRITE -> MF_READ | MF_WRITE）而异。
    ///
    /// \r error_success if the function was successful, or an error_code
    /// describing the failure if an error occurred.
    ///
    /// \r 如果函数成功，返回 error_success；如果发生错误，返回描述失败的 error_code。
    virtual std::error_code protectMappedMemory(const sys::MemoryBlock &Block,
                                                unsigned Flags) = 0;

    /// This method releases a block of memory that was allocated with the
    /// allocateMappedMemory method. It should not be used to release any memory
    /// block allocated any other way.
    /// \p Block describes the memory to be released.
    ///
    /// 此方法释放使用 allocateMappedMemory 方法分配的内存块。它不应用于释放以任何其他方式分配的内存块。
    /// \p Block 描述要释放的内存。
    ///
    /// \r error_success if the function was successful, or an error_code
    /// describing the failure if an error occurred.
    ///
    /// \r 如果函数成功，返回 error_success；如果发生错误，返回描述失败的 error_code。
    virtual std::error_code releaseMappedMemory(sys::MemoryBlock &M) = 0;

    virtual ~MemoryMapper();
  };

  /// Creates a SectionMemoryManager instance with \p MM as the associated
  /// memory mapper.  If \p MM is nullptr then a default memory mapper is used
  /// that directly calls into the operating system.
  ///
  /// 创建一个 SectionMemoryManager 实例，并将 \p MM 作为关联的内存映射器。
  /// 如果 \p MM 为 nullptr，则使用默认的内存映射器，直接调用操作系统。
  ///
  /// If \p ReserveAlloc is true all memory will be pre-allocated, and any
  /// attempts to allocate beyond pre-allocated memory will fail.
  ///
  /// 如果 \p ReserveAlloc 为 true，则所有内存都将被预分配，任何超出预分配内存的分配尝试都将失败。
  SectionMemoryManager(MemoryMapper *MM = nullptr, bool ReserveAlloc = false);
  SectionMemoryManager(const SectionMemoryManager &) = delete;
  void operator=(const SectionMemoryManager &) = delete;
  ~SectionMemoryManager() override;

  /// Enable reserveAllocationSpace when requested.
  ///
  /// 请求时启用 reserveAllocationSpace。
  bool needsToReserveAllocationSpace() override { return ReserveAllocation; }

  /// Implements allocating all memory in a single block. This is required to
  /// limit memory offsets to fit the ARM ABI; large memory systems may
  /// otherwise allocate separate sections too far apart.
  ///
  /// 实现将所有内存分配在一个块中。这是为了限制内存偏移量以适应 ARM ABI；
  /// 否则，大型内存系统可能会将各个节分配得相距太远。
#if LLVM_VERSION_MAJOR < 16
  virtual void reserveAllocationSpace(uintptr_t CodeSize, uint32_t CodeAlign,
                                      uintptr_t RODataSize,
                                      uint32_t RODataAlign,
                                      uintptr_t RWDataSize,
                                      uint32_t RWDataAlign) override;
#else
  void reserveAllocationSpace(uintptr_t CodeSize, Align CodeAlign,
                              uintptr_t RODataSize, Align RODataAlign,
                              uintptr_t RWDataSize, Align RWDataAlign) override;
#endif

  /// Allocates a memory block of (at least) the given size suitable for
  /// executable code.
  ///
  /// 分配一个（至少）为给定大小的、适用于可执行代码的内存块。
  ///
  /// The value of \p Alignment must be a power of two.  If \p Alignment is zero
  /// a default alignment of 16 will be used.
  ///
  /// \p Alignment 的值必须是 2 的幂。如果 \p Alignment 为零，将使用默认对齐值 16。
  uint8_t *allocateCodeSection(uintptr_t Size, unsigned Alignment,
                               unsigned SectionID,
                               StringRef SectionName) override;

  /// Allocates a memory block of (at least) the given size suitable for
  /// executable code.
  ///
  /// 分配一个（至少）为给定大小的、适用于代码生成的内存块（此处指数据段）。
  ///
  /// The value of \p Alignment must be a power of two.  If \p Alignment is zero
  /// a default alignment of 16 will be used.
  ///
  /// \p Alignment 的值必须是 2 的幂。如果 \p Alignment 为零，将使用默认对齐值 16。
  uint8_t *allocateDataSection(uintptr_t Size, unsigned Alignment,
                               unsigned SectionID, StringRef SectionName,
                               bool IsReadOnly) override;

  /// Update section-specific memory permissions and other attributes.
  ///
  /// 更新特定于节的内存权限和其他属性。
  ///
  /// This method is called when object loading is complete and section page
  /// permissions can be applied.  It is up to the memory manager implementation
  /// to decide whether or not to act on this method.  The memory manager will
  /// typically allocate all sections as read-write and then apply specific
  /// permissions when this method is called.  Code sections cannot be executed
  /// until this function has been called.  In addition, any cache coherency
  /// operations needed to reliably use the memory are also performed.
  ///
  /// 当对象加载完成且可以应用节页面权限时，将调用此方法。内存管理器实现可以决定是否对此方法采取行动。
  /// 内存管理器通常会将所有节分配为读写模式，然后在调用此方法时应用特定的最终权限。
  /// 在调用此函数之前，代码节无法执行。此外，还会执行可靠使用内存所需的任何缓存一致性操作（如刷新指令缓存）。
  ///
  /// \returns true if an error occurred, false otherwise.
  ///
  /// \returns 如果发生错误，返回 true，否则返回 false。
  bool finalizeMemory(std::string *ErrMsg = nullptr) override;

  /// Invalidate instruction cache for code sections.
  ///
  /// 使代码节的指令缓存失效。
  ///
  /// Some platforms with separate data cache and instruction cache require
  /// explicit cache flush, otherwise JIT code manipulations (like resolved
  /// relocations) will get to the data cache but not to the instruction cache.
  ///
  /// 某些具有独立数据缓存和指令缓存的平台需要显式的缓存刷新，否则 JIT 代码操作
  /// （例如解析后的重定位）将进入数据缓存而非指令缓存。
  ///
  /// This method is called from finalizeMemory.
  ///
  /// 此方法在 finalizeMemory 中被调用。
  virtual void invalidateInstructionCache();

private:
  struct FreeMemBlock {
    // The actual block of free memory
    // 实际的空闲内存块
    sys::MemoryBlock Free;
    // If there is a pending allocation from the same reservation right before
    // this block, store its index in PendingMem, to be able to update the
    // pending region if part of this block is allocated, rather than having to
    // create a new one
    // 如果在此块之前紧接着来自同一预留空间的待处理分配，则将其在 PendingMem 中的索引存储起来，
    // 以便在分配此块的一部分时能够更新待处理区域，而无需创建一个新的区域。
    unsigned PendingPrefixIndex;
  };

  struct MemoryGroup {
    // PendingMem contains all blocks of memory (subblocks of AllocatedMem)
    // which have not yet had their permissions applied, but have been given
    // out to the user. FreeMem contains all block of memory, which have
    // neither had their permissions applied, nor been given out to the user.
    //
    // PendingMem 包含所有尚未应用权限但已分发给用户的内存块（AllocatedMem 的子块）。
    // FreeMem 包含所有既未应用权限也未分发给用户的内存块。
    SmallVector<sys::MemoryBlock, 16> PendingMem;
    SmallVector<FreeMemBlock, 16> FreeMem;

    // All memory blocks that have been requested from the system
    // 所有已向系统请求的内存块
    SmallVector<sys::MemoryBlock, 16> AllocatedMem;

    sys::MemoryBlock Near;
  };

  /// 内部辅助函数：根据用途从对应的内存组中分配空间。
  uint8_t *allocateSection(AllocationPurpose Purpose, uintptr_t Size,
                           unsigned Alignment);

  /// 内部辅助函数：递归遍历内存组中的所有块并应用保护标志。
  std::error_code applyMemoryGroupPermissions(MemoryGroup &MemGroup,
                                              unsigned Permissions);

  /// 内部辅助函数：检查内存组是否还有足够的连续空间来满足请求。
  bool hasSpace(const MemoryGroup &MemGroup, uintptr_t Size) const;

  void anchor() override;

  MemoryGroup CodeMem;
  MemoryGroup RWDataMem;
  MemoryGroup RODataMem;
  MemoryMapper *MMapper;
  std::unique_ptr<MemoryMapper> OwnedMMapper;
  bool ReserveAllocation;
};

} // end namespace backport
} // end namespace llvm

#endif // LLVM_EXECUTIONENGINE_BACKPORT_SECTIONMEMORYMANAGER_H
